var hutIconUrl = "resources/icons/hut32.png"
var campsiteIconUrl = "resources/icons/campsite32.png"
var caveIconUrl = "resources/icons/cave32.png"
var waterfallIconUrl = "resources/icons/waterfall32.png"
var hutGrayIconUrl = "resources/icons/hut32-gray.png"
var campsiteGrayIconUrl = "resources/icons/campsite32-gray.png"
var caveGrayIconUrl = "resources/icons/cave32-gray.png"
var waterfallGrayIconUrl = "resources/icons/waterfall32-gray.png"

var fetch_huts_url = "http://borche-api.pentatope.co.uk/huts"
var fetch_campsites_url = "http://borche-api.pentatope.co.uk/campsites"
var fetch_caves_url = "http://borche-api.pentatope.co.uk/caves"
var fetch_waterfalls_url = "http://borche-api.pentatope.co.uk/waterfalls"
var fetch_paths_url = "http://borche-api.pentatope.co.uk/paths"